"""
COMPREHENSIVE DATABASE SCHEMA FOR 462+ COLUMNS
This module defines the complete database schema for asset management
including all hardware, software, network, security, and management fields
"""

# COMPREHENSIVE ASSET MANAGEMENT COLUMNS (462+ fields)
COMPREHENSIVE_COLUMNS = {
    # === BASIC IDENTIFICATION (20 columns) ===
    'id': 'INTEGER PRIMARY KEY AUTOINCREMENT',
    'hostname': 'TEXT',
    'computer_name': 'TEXT',
    'device_hostname': 'TEXT',
    'domain_hostname': 'TEXT',
    'dns_hostname': 'TEXT',
    'netbios_name': 'TEXT',
    'fqdn': 'TEXT',
    'ip_address': 'TEXT',
    'ipv6_address': 'TEXT',
    'mac_address': 'TEXT',
    'primary_mac': 'TEXT',
    'all_mac_addresses': 'TEXT',
    'hostname_mismatch_status': 'TEXT',
    'hostname_mismatch_details': 'TEXT',
    'device_guid': 'TEXT',
    'uuid': 'TEXT',
    'bios_uuid': 'TEXT',
    'asset_tag': 'TEXT',
    'service_tag': 'TEXT',
    
    # === DOMAIN AND NETWORK IDENTITY (15 columns) ===
    'domain_name': 'TEXT',
    'workgroup': 'TEXT',
    'domain_controller': 'TEXT',
    'dns_servers': 'TEXT',
    'dns_suffix': 'TEXT',
    'dhcp_enabled': 'BOOLEAN',
    'dhcp_server': 'TEXT',
    'wins_servers': 'TEXT',
    'gateway': 'TEXT',
    'subnet_mask': 'TEXT',
    'network_profile': 'TEXT',
    'domain_joined': 'BOOLEAN',
    'domain_role': 'TEXT',
    'ad_site': 'TEXT',
    'ou_path': 'TEXT',
    
    # === HARDWARE - SYSTEM (25 columns) ===
    'system_manufacturer': 'TEXT',
    'system_model': 'TEXT',
    'system_family': 'TEXT',
    'system_sku': 'TEXT',
    'system_version': 'TEXT',
    'chassis_type': 'TEXT',
    'form_factor': 'TEXT',
    'serial_number': 'TEXT',
    'motherboard_manufacturer': 'TEXT',
    'motherboard_model': 'TEXT',
    'motherboard_serial': 'TEXT',
    'motherboard_version': 'TEXT',
    'system_enclosure_type': 'TEXT',
    'system_enclosure_serial': 'TEXT',
    'system_power_supply': 'TEXT',
    'power_supply_wattage': 'INTEGER',
    'power_supply_manufacturer': 'TEXT',
    'cooling_system': 'TEXT',
    'thermal_design_power': 'INTEGER',
    'system_weight': 'REAL',
    'system_dimensions': 'TEXT',
    'rack_unit_size': 'INTEGER',
    'rack_position': 'TEXT',
    'datacenter_location': 'TEXT',
    'physical_location': 'TEXT',
    
    # === HARDWARE - PROCESSOR (30 columns) ===
    'processor_name': 'TEXT',
    'processor_manufacturer': 'TEXT',
    'processor_architecture': 'TEXT',
    'processor_family': 'TEXT',
    'processor_model': 'TEXT',
    'processor_stepping': 'TEXT',
    'processor_cores': 'INTEGER',
    'processor_logical_cores': 'INTEGER',
    'processor_threads': 'INTEGER',
    'processor_speed_mhz': 'INTEGER',
    'processor_max_speed_mhz': 'INTEGER',
    'processor_current_speed': 'INTEGER',
    'processor_base_speed': 'INTEGER',
    'processor_l1_cache_size': 'INTEGER',
    'processor_l2_cache_size': 'INTEGER',
    'processor_l3_cache_size': 'INTEGER',
    'processor_socket_type': 'TEXT',
    'processor_voltage': 'REAL',
    'processor_power_consumption': 'INTEGER',
    'processor_virtualization': 'BOOLEAN',
    'processor_hyper_threading': 'BOOLEAN',
    'processor_64bit_capable': 'BOOLEAN',
    'processor_instruction_set': 'TEXT',
    'processor_microcode_version': 'TEXT',
    'cpu_count': 'INTEGER',
    'cpu_usage_percent': 'REAL',
    'cpu_temperature': 'REAL',
    'cpu_fan_speed': 'INTEGER',
    'cpu_load_average': 'TEXT',
    'cpu_processes': 'INTEGER',
    
    # === HARDWARE - MEMORY (25 columns) ===
    'total_physical_memory_gb': 'REAL',
    'total_physical_memory_mb': 'INTEGER',
    'available_memory_gb': 'REAL',
    'used_memory_gb': 'REAL',
    'memory_usage_percent': 'REAL',
    'memory_slots_used': 'INTEGER',
    'memory_slots_total': 'INTEGER',
    'memory_modules': 'TEXT',
    'memory_type': 'TEXT',
    'memory_speed_mhz': 'INTEGER',
    'memory_form_factor': 'TEXT',
    'memory_voltage': 'REAL',
    'memory_ecc_enabled': 'BOOLEAN',
    'memory_registered': 'BOOLEAN',
    'memory_dual_channel': 'BOOLEAN',
    'virtual_memory_total': 'REAL',
    'virtual_memory_available': 'REAL',
    'virtual_memory_used': 'REAL',
    'page_file_size': 'REAL',
    'page_file_usage': 'REAL',
    'swap_file_size': 'REAL',
    'cache_size_l1': 'INTEGER',
    'cache_size_l2': 'INTEGER',
    'cache_size_l3': 'INTEGER',
    'memory_manufacturer': 'TEXT',
    
    # === HARDWARE - STORAGE (35 columns) ===
    'storage_devices': 'TEXT',
    'total_storage_gb': 'REAL',
    'available_storage_gb': 'REAL',
    'used_storage_gb': 'REAL',
    'storage_summary': 'TEXT',
    'disk_usage_percent': 'REAL',
    'primary_drive_type': 'TEXT',
    'primary_drive_size': 'REAL',
    'primary_drive_free': 'REAL',
    'ssd_count': 'INTEGER',
    'hdd_count': 'INTEGER',
    'optical_drives': 'TEXT',
    'usb_drives': 'TEXT',
    'network_drives': 'TEXT',
    'raid_configuration': 'TEXT',
    'raid_level': 'TEXT',
    'raid_status': 'TEXT',
    'disk_controller': 'TEXT',
    'sata_version': 'TEXT',
    'nvme_drives': 'TEXT',
    'storage_encryption': 'TEXT',
    'bitlocker_status': 'TEXT',
    'disk_health_status': 'TEXT',
    'smart_status': 'TEXT',
    'disk_temperature': 'TEXT',
    'disk_read_speed': 'TEXT',
    'disk_write_speed': 'TEXT',
    'disk_iops': 'TEXT',
    'partition_layout': 'TEXT',
    'file_systems': 'TEXT',
    'mount_points': 'TEXT',
    'volume_serial_numbers': 'TEXT',
    'disk_serial_numbers': 'TEXT',
    'storage_firmware': 'TEXT',
    'backup_devices': 'TEXT',
    
    # === HARDWARE - GRAPHICS (20 columns) ===
    'graphics_cards': 'TEXT',
    'primary_graphics_card': 'TEXT',
    'graphics_manufacturer': 'TEXT',
    'graphics_model': 'TEXT',
    'graphics_memory_mb': 'INTEGER',
    'graphics_memory_type': 'TEXT',
    'graphics_driver_version': 'TEXT',
    'graphics_driver_date': 'TEXT',
    'graphics_bios_version': 'TEXT',
    'graphics_cuda_cores': 'INTEGER',
    'graphics_directx_version': 'TEXT',
    'graphics_opengl_version': 'TEXT',
    'graphics_vulkan_support': 'BOOLEAN',
    'multiple_gpu_setup': 'TEXT',
    'integrated_graphics': 'BOOLEAN',
    'dedicated_graphics': 'BOOLEAN',
    'graphics_power_consumption': 'INTEGER',
    'graphics_temperature': 'REAL',
    'graphics_fan_speed': 'INTEGER',
    'external_gpu': 'BOOLEAN',
    
    # === HARDWARE - DISPLAY (15 columns) ===
    'connected_monitors': 'INTEGER',
    'monitor_details': 'TEXT',
    'screen_resolution': 'TEXT',
    'display_adapters': 'TEXT',
    'primary_monitor_size': 'TEXT',
    'primary_monitor_resolution': 'TEXT',
    'monitor_refresh_rate': 'TEXT',
    'monitor_manufacturers': 'TEXT',
    'monitor_serial_numbers': 'TEXT',
    'color_depth': 'TEXT',
    'hdr_support': 'BOOLEAN',
    'support_4k': 'BOOLEAN',
    'multi_monitor_setup': 'BOOLEAN',
    'display_scaling': 'TEXT',
    'display_orientation': 'TEXT',
    
    # === HARDWARE - NETWORK ADAPTERS (25 columns) ===
    'network_adapters': 'TEXT',
    'ethernet_adapters': 'TEXT',
    'wireless_adapters': 'TEXT',
    'network_configuration': 'TEXT',
    'wifi_card_model': 'TEXT',
    'wifi_driver_version': 'TEXT',
    'bluetooth_enabled': 'BOOLEAN',
    'bluetooth_version': 'TEXT',
    'network_speed': 'TEXT',
    'duplex_mode': 'TEXT',
    'link_status': 'TEXT',
    'network_utilization': 'TEXT',
    'tcp_connections': 'INTEGER',
    'udp_connections': 'INTEGER',
    'network_protocols': 'TEXT',
    'vlan_configuration': 'TEXT',
    'network_teaming': 'TEXT',
    'wake_on_lan': 'BOOLEAN',
    'network_boot': 'BOOLEAN',
    'pxe_support': 'BOOLEAN',
    'network_security': 'TEXT',
    'vpn_connections': 'TEXT',
    'proxy_settings': 'TEXT',
    'network_shares': 'TEXT',
    'network_printers': 'TEXT',
    
    # === HARDWARE - PERIPHERALS (20 columns) ===
    'usb_devices': 'TEXT',
    'keyboard_type': 'TEXT',
    'mouse_type': 'TEXT',
    'audio_devices': 'TEXT',
    'speakers': 'TEXT',
    'microphone': 'TEXT',
    'webcam': 'TEXT',
    'printers': 'TEXT',
    'scanners': 'TEXT',
    'external_storage': 'TEXT',
    'docking_station': 'TEXT',
    'kvm_switch': 'TEXT',
    'ups_device': 'TEXT',
    'serial_ports': 'TEXT',
    'parallel_ports': 'TEXT',
    'firewire_ports': 'TEXT',
    'thunderbolt_ports': 'TEXT',
    'usb_port_count': 'INTEGER',
    'peripheral_drivers': 'TEXT',
    'device_manager_issues': 'TEXT',
    
    # === OPERATING SYSTEM (30 columns) ===
    'operating_system': 'TEXT',
    'os_version': 'TEXT',
    'os_build': 'TEXT',
    'os_edition': 'TEXT',
    'os_architecture': 'TEXT',
    'os_service_pack': 'TEXT',
    'os_install_date': 'TEXT',
    'os_last_boot_time': 'TEXT',
    'os_uptime': 'TEXT',
    'os_kernel_version': 'TEXT',
    'os_language': 'TEXT',
    'os_timezone': 'TEXT',
    'os_product_key': 'TEXT',
    'os_activation_status': 'TEXT',
    'os_license_type': 'TEXT',
    'windows_update_status': 'TEXT',
    'pending_reboots': 'INTEGER',
    'boot_mode': 'TEXT',
    'secure_boot': 'BOOLEAN',
    'tpm_version': 'TEXT',
    'tpm_enabled': 'BOOLEAN',
    'system_restore_enabled': 'BOOLEAN',
    'hibernation_enabled': 'BOOLEAN',
    'fast_startup_enabled': 'BOOLEAN',
    'registry_size': 'INTEGER',
    'temp_folder_size': 'REAL',
    'page_file_location': 'TEXT',
    'system_drive': 'TEXT',
    'windows_folder': 'TEXT',
    'program_files_folder': 'TEXT',
    
    # === BIOS/FIRMWARE (15 columns) ===
    'bios_manufacturer': 'TEXT',
    'bios_version': 'TEXT',
    'bios_release_date': 'TEXT',
    'bios_serial_number': 'TEXT',
    'firmware_type': 'TEXT',
    'uefi_enabled': 'BOOLEAN',
    'uefi_version': 'TEXT',
    'bios_settings': 'TEXT',
    'boot_order': 'TEXT',
    'legacy_boot_enabled': 'BOOLEAN',
    'virtualization_enabled': 'BOOLEAN',
    'intel_vt_enabled': 'BOOLEAN',
    'amd_v_enabled': 'BOOLEAN',
    'firmware_update_available': 'BOOLEAN',
    'smbios_version': 'TEXT',
    
    # === SOFTWARE - INSTALLED PROGRAMS (25 columns) ===
    'installed_software': 'TEXT',
    'installed_software_count': 'INTEGER',
    'software_inventory': 'TEXT',
    'microsoft_office_version': 'TEXT',
    'adobe_products': 'TEXT',
    'development_tools': 'TEXT',
    'media_software': 'TEXT',
    'security_software': 'TEXT',
    'productivity_software': 'TEXT',
    'system_utilities': 'TEXT',
    'games_installed': 'TEXT',
    'portable_software': 'TEXT',
    'recently_installed': 'TEXT',
    'startup_programs': 'TEXT',
    'scheduled_tasks': 'TEXT',
    'windows_features': 'TEXT',
    'optional_features': 'TEXT',
    'runtimes_installed': 'TEXT',
    'drivers_installed': 'TEXT',
    'codecs_installed': 'TEXT',
    'fonts_installed': 'TEXT',
    'software_licenses': 'TEXT',
    'trial_software': 'TEXT',
    'expired_software': 'TEXT',
    'software_updates_pending': 'TEXT',
    
    # === SOFTWARE - UPDATES AND PATCHES (20 columns) ===
    'installed_updates': 'TEXT',
    'windows_updates': 'TEXT',
    'security_updates': 'TEXT',
    'critical_updates': 'TEXT',
    'optional_updates': 'TEXT',
    'driver_updates': 'TEXT',
    'software_updates': 'TEXT',
    'pending_updates': 'TEXT',
    'failed_updates': 'TEXT',
    'update_history': 'TEXT',
    'last_update_check': 'TEXT',
    'automatic_updates_enabled': 'BOOLEAN',
    'wsus_server': 'TEXT',
    'update_source': 'TEXT',
    'reboot_required': 'BOOLEAN',
    'patch_level': 'TEXT',
    'vulnerability_status': 'TEXT',
    'hotfixes_installed': 'TEXT',
    'service_packs': 'TEXT',
    'cumulative_updates': 'TEXT',
    
    # === SOFTWARE - BROWSERS AND INTERNET (15 columns) ===
    'browsers_installed': 'TEXT',
    'default_browser': 'TEXT',
    'browser_versions': 'TEXT',
    'browser_extensions': 'TEXT',
    'browser_bookmarks': 'TEXT',
    'browser_history_enabled': 'BOOLEAN',
    'browser_cache_size': 'REAL',
    'browser_security_settings': 'TEXT',
    'java_version': 'TEXT',
    'flash_version': 'TEXT',
    'silverlight_version': 'TEXT',
    'internet_explorer_version': 'TEXT',
    'edge_version': 'TEXT',
    'chrome_version': 'TEXT',
    'firefox_version': 'TEXT',
    
    # === SECURITY (30 columns) ===
    'antivirus_software': 'TEXT',
    'antivirus_version': 'TEXT',
    'antivirus_status': 'TEXT',
    'antivirus_last_scan': 'TEXT',
    'antivirus_definitions_date': 'TEXT',
    'antivirus_real_time_protection': 'BOOLEAN',
    'windows_defender_status': 'TEXT',
    'windows_defender_version': 'TEXT',
    'firewall_status': 'TEXT',
    'firewall_profile': 'TEXT',
    'firewall_rules': 'TEXT',
    'windows_firewall_enabled': 'BOOLEAN',
    'third_party_firewall': 'TEXT',
    'encryption_status': 'TEXT',
    'bitlocker_enabled': 'BOOLEAN',
    'file_vault_enabled': 'BOOLEAN',
    'disk_encryption': 'TEXT',
    'uac_status': 'TEXT',
    'uac_level': 'TEXT',
    'security_center_status': 'TEXT',
    'malware_protection': 'TEXT',
    'spyware_protection': 'TEXT',
    'ransomware_protection': 'TEXT',
    'exploit_protection': 'TEXT',
    'attack_surface_reduction': 'TEXT',
    'controlled_folder_access': 'TEXT',
    'network_protection': 'TEXT',
    'device_security': 'TEXT',
    'credential_guard': 'BOOLEAN',
    'device_guard': 'BOOLEAN',
    
    # === USER ACCOUNTS (20 columns) ===
    'current_user': 'TEXT',
    'current_user_domain': 'TEXT',
    'current_user_sid': 'TEXT',
    'user_profiles': 'TEXT',
    'local_users': 'TEXT',
    'domain_users': 'TEXT',
    'administrator_accounts': 'TEXT',
    'guest_account_enabled': 'BOOLEAN',
    'last_logged_users': 'TEXT',
    'user_login_history': 'TEXT',
    'user_groups': 'TEXT',
    'user_privileges': 'TEXT',
    'password_policy': 'TEXT',
    'account_lockout_policy': 'TEXT',
    'user_access_control': 'TEXT',
    'roaming_profiles': 'TEXT',
    'user_certificates': 'TEXT',
    'user_registry_size': 'TEXT',
    'user_temp_folders': 'TEXT',
    'registered_owner': 'TEXT',
    
    # === PERFORMANCE METRICS (25 columns) ===
    'system_uptime_hours': 'REAL',
    'cpu_usage_average': 'REAL',
    'memory_usage_average': 'REAL',
    'disk_queue_length': 'REAL',
    'network_throughput': 'REAL',
    'system_responsiveness': 'TEXT',
    'boot_time_seconds': 'REAL',
    'login_time_seconds': 'REAL',
    'application_launch_time': 'REAL',
    'file_copy_speed': 'REAL',
    'disk_read_rate': 'REAL',
    'disk_write_rate': 'REAL',
    'network_latency': 'REAL',
    'page_faults_per_sec': 'REAL',
    'context_switches_per_sec': 'REAL',
    'interrupt_rate': 'REAL',
    'processor_queue_length': 'REAL',
    'available_bytes': 'INTEGER',
    'committed_bytes': 'INTEGER',
    'pool_nonpaged_bytes': 'INTEGER',
    'pool_paged_bytes': 'INTEGER',
    'system_cache_resident_bytes': 'INTEGER',
    'system_driver_resident_bytes': 'INTEGER',
    'processes_count': 'INTEGER',
    'threads_count': 'INTEGER',
    
    # === MANAGEMENT AND ORGANIZATION (25 columns) ===
    'department': 'TEXT',
    'assigned_department': 'TEXT',
    'location': 'TEXT',
    'site': 'TEXT',
    'building': 'TEXT',
    'floor': 'TEXT',
    'room': 'TEXT',
    'desk_location': 'TEXT',
    'cost_center': 'TEXT',
    'budget_code': 'TEXT',
    'asset_owner': 'TEXT',
    'primary_user': 'TEXT',
    'backup_user': 'TEXT',
    'it_contact': 'TEXT',
    'support_group': 'TEXT',
    'maintenance_window': 'TEXT',
    'business_criticality': 'TEXT',
    'compliance_requirements': 'TEXT',
    'data_classification': 'TEXT',
    'backup_schedule': 'TEXT',
    'monitoring_enabled': 'BOOLEAN',
    'alerts_configured': 'TEXT',
    'documentation_links': 'TEXT',
    'change_management': 'TEXT',
    'approval_required': 'BOOLEAN',
    
    # === ASSET LIFECYCLE (20 columns) ===
    'purchase_date': 'TEXT',
    'purchase_order': 'TEXT',
    'vendor': 'TEXT',
    'supplier': 'TEXT',
    'purchase_price': 'REAL',
    'depreciation_method': 'TEXT',
    'depreciation_rate': 'REAL',
    'current_value': 'REAL',
    'lease_information': 'TEXT',
    'warranty_provider': 'TEXT',
    'warranty_expiry': 'TEXT',
    'warranty_type': 'TEXT',
    'service_contract': 'TEXT',
    'maintenance_schedule': 'TEXT',
    'next_maintenance': 'TEXT',
    'end_of_life': 'TEXT',
    'replacement_scheduled': 'TEXT',
    'disposal_method': 'TEXT',
    'asset_status': 'TEXT',
    'lifecycle_stage': 'TEXT',
    
    # === COLLECTION METADATA (20 columns) ===
    'collection_method': 'TEXT',
    'collection_timestamp': 'TEXT',
    'collection_duration_seconds': 'REAL',
    'collection_id': 'TEXT',
    'collector_version': 'TEXT',
    'wmi_collection_success': 'BOOLEAN',
    'wmi_collection_errors': 'TEXT',
    'ssh_collection_success': 'BOOLEAN',
    'ssh_collection_errors': 'TEXT',
    'snmp_collection_success': 'BOOLEAN',
    'snmp_collection_errors': 'TEXT',
    'registry_access_success': 'BOOLEAN',
    'file_system_access_success': 'BOOLEAN',
    'network_scan_success': 'BOOLEAN',
    'data_completeness_score': 'REAL',
    'data_quality_score': 'REAL',
    'collection_attempts': 'INTEGER',
    'last_successful_collection': 'TEXT',
    'collection_schedule': 'TEXT',
    'next_collection': 'TEXT',
    
    # === CHANGE TRACKING (15 columns) ===
    'last_hardware_change': 'TEXT',
    'last_software_change': 'TEXT',
    'configuration_hash': 'TEXT',
    'change_history': 'TEXT',
    'hardware_changes': 'TEXT',
    'software_changes': 'TEXT',
    'configuration_changes': 'TEXT',
    'security_changes': 'TEXT',
    'network_changes': 'TEXT',
    'baseline_configuration': 'TEXT',
    'configuration_drift': 'TEXT',
    'change_detection_enabled': 'BOOLEAN',
    'change_notification': 'TEXT',
    'compliance_status': 'TEXT',
    'audit_trail': 'TEXT',
    
    # === DEVICE STATUS AND MONITORING (15 columns) ===
    'device_status': 'TEXT',
    'connectivity_status': 'TEXT',
    'health_status': 'TEXT',
    'operational_status': 'TEXT',
    'last_seen': 'TEXT',
    'ping_response_ms': 'INTEGER',
    'response_time': 'REAL',
    'availability_percentage': 'REAL',
    'uptime_percentage': 'REAL',
    'maintenance_mode': 'BOOLEAN',
    'monitoring_agent_status': 'TEXT',
    'remote_access_enabled': 'BOOLEAN',
    'remote_desktop_enabled': 'BOOLEAN',
    'wake_on_lan_enabled': 'BOOLEAN',
    'power_management': 'TEXT',
    
    # === CLASSIFICATION AND CATEGORIZATION (10 columns) ===
    'os_family': 'TEXT',
    'device_type': 'TEXT',
    'device_category': 'TEXT',
    'device_role': 'TEXT',
    'device_environment': 'TEXT',
    'criticality_level': 'TEXT',
    'risk_level': 'TEXT',
    'compliance_level': 'TEXT',
    'security_level': 'TEXT',
    'asset_classification': 'TEXT',
    
    # === SYSTEM TIMESTAMPS (5 columns) ===
    'created_at': 'TIMESTAMP DEFAULT CURRENT_TIMESTAMP',
    'updated_at': 'TIMESTAMP DEFAULT CURRENT_TIMESTAMP',
    'first_discovered': 'TIMESTAMP',
    'last_modified': 'TIMESTAMP',
    'data_retention_date': 'TIMESTAMP'
}

# Validate we have 462+ columns
print(f"Total comprehensive columns defined: {len(COMPREHENSIVE_COLUMNS)}")
assert len(COMPREHENSIVE_COLUMNS) >= 462, f"Need at least 462 columns, only have {len(COMPREHENSIVE_COLUMNS)}"